steps:
# Deploy bot
- name: 'gcr.io/cloud-builders/gcloud'
  id: DEPLOY
  entrypoint: 'bash'
  secretEnv: ['OWM_KEY', 'TELEBOT_KEY', 'WEBHOOK_TOKEN']
  args:
    - '-c'
    - |
      gcloud functions deploy $_NAME \
        --runtime $_RUNTIME \
        --region $_REGION \
        --source $_SOURCE \
        --entry-point $_ENTRY_POINT \
        --allow-unauthenticated \
        --trigger-http \
        --memory $_MEMORY \
        --max-instances $_MAX_INSTANCES \
        --concurrency $_CONCURRENCY \
        --set-env-vars OWM_KEY=$$OWM_KEY,TELEBOT_KEY=$$TELEBOT_KEY,WEBHOOK_TOKEN=$$WEBHOOK_TOKEN

# Configure webhook
- name: 'gcr.io/cloud-builders/gcloud'
  id: WEBHOOK
  entrypoint: 'bash'
  secretEnv: ['TELEBOT_KEY', 'WEBHOOK_TOKEN']
  args:
    - '-c'
    - |
      # Get function URL
      URL=$(gcloud functions describe $_NAME \
        --gen2 \
        --region $_REGION \
        --format='value(serviceConfig.uri)')
      echo "Function URL: $$URL"

      #Remove previous webhook
      curl -s -X POST "https://api.telegram.org/bot$$TELEBOT_KEY/deleteWebhook"

      # Set webhook
      curl -s -X POST "https://api.telegram.org/bot$$TELEBOT_KEY/setWebhook" \
        -F "url=$$URL" \
        -F "secret_token=$$WEBHOOK_TOKEN"


substitutions:
    _REGION                       : us-east1
    _NAME                         : skbweatherbot
    _RUNTIME                      : python310
    _ENTRY_POINT                  : webhook_run
    _SOURCE                       : ./src/
    _MEMORY                       : 512MB
    _MAX_INSTANCES                : '3'
    _CONCURRENCY                  : '1'
    _SM_OWM_KEY_SECRET_NAME       : WEATHERBOT_OWM_KEY
    _SM_TELEBOT_KEY_SECRET_NAME   : WEATHERBOT_TELEGRAM_KEY
    _SM_WEBHOOK_TOKEN_SECRET_NAME : WEATHERBOT_WEBHOOK_TOKEN


availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/${_SM_OWM_KEY_SECRET_NAME}/versions/latest
    env: OWM_KEY
  - versionName: projects/${PROJECT_ID}/secrets/${_SM_TELEBOT_KEY_SECRET_NAME}/versions/latest
    env: TELEBOT_KEY
  - versionName: projects/${PROJECT_ID}/secrets/${_SM_WEBHOOK_TOKEN_SECRET_NAME}/versions/latest
    env: WEBHOOK_TOKEN


timeout: 600s